### ISSUE TITLE
作業時間が異常なほど大きくなる不具合

### ISSUE THREAD

**Issue by UNE-fun** [touhouota/task_scheduler#72]
タスクを実行中に、他のタスクの実行を押すと2つの作業時間がどちらも大体236時間と異常なほど大きくなる不具合を発見しました。
他のタスクを押したりして試してみましたがどうやらタスクによってバグる時間は違うらしいです。
再度開始すると、バグった時間からスタートされるみたいです。
![image](https://user-images.githubusercontent.com/40259661/41514632-8be6c636-72e3-11e8-9f18-6066c5bde3c1.png)

**Comment by touhouota** [comment]
ありがてぇ。
公開時に起きていた問題と同様であろうと思うので、さっくり直してみますね。

**Comment by touhouota** [comment]
公開時に起きた問題とは別だった件。
とりあえず、修正してみました。
