### ISSUE TITLE
入力したタスクが消えたように思える

### ISSUE THREAD

**Issue by mima-fun-lab** [touhouota/task_scheduler#73]
使い方がわかっていないのかもしれないけど、入力したタスクが消えたようです。
とりあえず、関心事がslackにあるのだろうから、こちらは、このままでもよいのかもしれませんが、不安定なところがきになります。

**Comment by touhouota** [comment]
コードを整理したときに、パスとRails側で処理するところの連携を修正し忘れていたようです。
修正しました。
