### ISSUE TITLE
タスクのタイマー止めるのわすれた

### ISSUE THREAD

**Issue by mima-fun-lab** [touhouota/task_scheduler#75]
というわけで経過した時間を訂正したいとおもった

**Comment by touhouota** [comment]
修正モーダルに、作業時間を修正するための入力欄を設けてみました。
![2018-07-29 23 59 34](https://user-images.githubusercontent.com/13186385/43367653-819ed6dc-938b-11e8-91cb-ce87744caca2.png)

後ほど、ボタン等により修正できるようなモノもつけたいと思います。
